# Generated by Django 6.0.4 on 2026-05-16 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_registroocorrenciaaluno_unico_registro_por_aluno_data_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(help_text='Nome completo do professor', max_length=200, verbose_name='Nome do Professor')),
                ('email_professor', models.EmailField(help_text='E-mail para contato', max_length=254, verbose_name='E-mail do Professor')),
                ('tipo_aviso', models.CharField(choices=[('atraso', '⏰ Atraso'), ('falta', '❌ Falta no dia'), ('atestado', '📋 Atestado'), ('outro', '📝 Outra justificativa')], max_length=20, verbose_name='Tipo de Aviso')),
                ('descricao', models.TextField(help_text='Descreva os detalhes do seu aviso', verbose_name='Descrição/Justificativa')),
                ('data_aviso', models.DateField(help_text='Qual é a data em questão?', verbose_name='Data do aviso')),
                ('visualizado', models.BooleanField(default=False, verbose_name='Visualizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('visualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Visualizado em')),
                ('visualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_professor_visualizados', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por')),
            ],
            options={
                'verbose_name': 'Aviso de Professor',
                'verbose_name_plural': 'Avisos de Professores',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['-data_criacao'], name='apps_avisop_data_cr_59d5b6_idx'), models.Index(fields=['visualizado'], name='apps_avisop_visuali_438388_idx')],
            },
        ),
    ]
