# Generated by Django for the public teacher notice feature.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_registroocorrenciaaluno_unico_registro_por_aluno_data_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_nome', models.CharField(max_length=200, verbose_name='Professor / Nome completo')),
                ('disciplina', models.CharField(max_length=120)),
                ('dia', models.DateField()),
                ('motivo', models.CharField(choices=[('falta', 'Falta'), ('atestado', 'Atestado'), ('atraso', 'Atraso')], max_length=20)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                ('visualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_professores_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de Professor',
                'verbose_name_plural': 'Avisos de Professores',
                'ordering': ['status', '-dia', '-criado_em'],
            },
        ),
    ]
