# Generated by Django for registrar_ocorrencia_aluno turno validation.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_avisoprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroocorrenciaaluno',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], default='manha', max_length=10, verbose_name='Turno'),
        ),
    ]
