# Generated by Django 6.0.4 on 2026-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_avisoprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisoprofessor',
            name='dias_atestado',
            field=models.IntegerField(blank=True, help_text="Preencha apenas se o tipo for 'Atestado'", null=True, verbose_name='Quantos dias de atestado'),
        ),
    ]
